task: beavertails
dataset_path: PKU-Alignment/BeaverTails-Evaluation
dataset_name: default
test_split: test
output_type: generate_until
doc_to_text: "{{prompt}}"
doc_to_target: ""
generation_kwargs:
  until:
    - "</s>"
    - "<|endoftext|>"
    - ".\n\nA"
    - ".\n\nB"
    - ".\n\nC"
    - ".\n\nD"
    - ".\n\nE"
    - ".\n\nF"
    - ".\n\nG"
    - ".\n\nH"
    - ".\n\nI"
    - ".\n\nJ"
    - ".\n\nK"
    - ".\n\nL"
    - ".\n\nM"
    - ".\n\nN"
    - ".\n\nO"
    - ".\n\nP"
    - ".\n\nQ"
    - ".\n\nR"
    - ".\n\nS"
    - ".\n\nT"
    - ".\n\nU"
    - ".\n\nV"
    - ".\n\nW"
    - ".\n\nX"
    - ".\n\nY"
    - ".\n\nZ"
  do_sample: false
  temperature: 0
  max_new_tokens: 16  # Refusals are short; 64 is plenty.
metric_list:
  - metric: bypass