task: beavertails
dataset_path: PKU-Alignment/BeaverTails-Evaluation
dataset_name: default
test_split: test
output_type: generate_until
doc_to_text: "{{prompt}}"
doc_to_target: ""
generation_kwargs:
  until:
    - "</s>"
    - "<|endoftext|>"
  do_sample: false
  temperature: 0
  max_new_tokens: 512
metric_list:
  - metric: bypass
