task: beavertails
dataset_path: PKU-Alignment/BeaverTails-Evaluation
dataset_name: default
test_split: test
output_type: generate_until
doc_to_text: "{{prompt}}"
doc_to_target: ""
generation_kwargs:
  until:
    - "</s>"
    - "<|endoftext|>"
    - "\n\n"          # Stops the model after it finishes its first main paragraph
    - "Question:"    # Prevents it from hallucinating a new question
  do_sample: false
  temperature: 0
  max_new_tokens: 128 # BeaverTails answers should be short; 512 is too high and allows more looping
metric_list:
  - metric: bypass